mongo:
  image: mongo:3.6.17
  ports:
   - "27017:27017"
  volumes:
   - './data:/data/db'
application:
  build: .
  command: bash -c "npm install; nodemon src/app.js --color=always"
  ports:
   - "8080:8080"
   - "5858:5858"
  volumes:
   - ./api:/usr/src/api
  links:
   - mongo